In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [3]:
type(a)

numpy.ndarray

In [5]:
print(a+b)
print(a*b)

[6 6 6 6 6]
[5 8 9 8 5]


In [6]:
x = np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [7]:
print(x.shape)

(2, 2)


In [8]:
print(x.ndim)

2


In [33]:
print(x.dtype)

int32


In [37]:
c = np.array([[[1,2],[2,3]],[[3,4],[4,5]]])
print(c)
print(c.ndim)
print(c.shape)
print(c.dtype)

[[[1 2]
  [2 3]]

 [[3 4]
  [4 5]]]
3
(2, 2, 2)
int32


In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
np.random.randint(10,40,size=(3,5))

array([[10, 28, 28, 20, 39],
       [36, 25, 39, 27, 18],
       [19, 35, 30, 33, 35]])

In [39]:
x = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])

y = np.array([[4,5,6],
              [8,9,5],
              [3,4,5]])

print(x)
print(y)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[4 5 6]
 [8 9 5]
 [3 4 5]]


In [40]:
print(x*y)

[[ 8 15 24]
 [40 54 35]
 [24 36 50]]


In [43]:
#matrix multiplication
print(x@y)

[[ 44  53  47]
 [ 89 107  95]
 [134 161 143]]


In [44]:
print(x.dot(y))

[[ 44  53  47]
 [ 89 107  95]
 [134 161 143]]


In [45]:
x.prod()

3628800

In [46]:
x.sum()

54

In [47]:
x.mean()

6.0

for each column

In [48]:
x.mean(axis=0)

array([5., 6., 7.])

for each row

In [49]:
x.mean(axis=1)

array([3., 6., 9.])

In [53]:
print(x.var())
print(x.std())
print(x.min())

6.666666666666667
2.581988897471611
2


In [58]:
z = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(z,25))
print(np.percentile(z,50))
print(np.percentile(z,75))

3.0
5.0
7.0


In [59]:
arr = np.array([[16,44,46,49],[10,22,41,35],[11,35,20,12],[46,33,42,36]])
print(arr)

[[16 44 46 49]
 [10 22 41 35]
 [11 35 20 12]
 [46 33 42 36]]


In [60]:
print('8x2')
print(arr.reshape(8,2))

8x2
[[16 44]
 [46 49]
 [10 22]
 [41 35]
 [11 35]
 [20 12]
 [46 33]
 [42 36]]


In [61]:
print('2x8')
print(arr.reshape(2,8))

2x8
[[16 44 46 49 10 22 41 35]
 [11 35 20 12 46 33 42 36]]
